<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Mosaddek">
    <meta name="keyword" content="FlatLab, Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
    <link rel="shortcut icon" href="{{ static_url('img/favicon.png')}}">

    <title>FlatLab - Flat & Responsive Bootstrap Admin Template</title>

    <!-- Bootstrap core CSS -->
    <link href="{{ static_url('css/bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{ static_url('css/bootstrap-reset.css')}}" rel="stylesheet">
    <!--external css-->
    <link href="{{ static_url('assets/font-awesome/css/font-awesome.css')}}" rel="stylesheet" />
    <link href="{{ static_url('assets/jquery-easy-pie-chart/jquery.easy-pie-chart.css')}}" rel="stylesheet" type="text/css" media="screen"/>
    <link rel="stylesheet" href="{{ static_url('css/owl.carousel.css')}}" type="text/css">
    <!-- Custom styles for this template -->
    <link href="{{ static_url('css/style.css')}}" rel="stylesheet">
    <link href="{{ static_url('css/style-responsive.css')}}" rel="stylesheet" />

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 tooltipss and media queries -->
    <!--[if lt IE 9]>
    <script src="{{ static_url('js/html5shiv.js')}}"></script>
    <script src="{{ static_url('js/respond.min.js')}}"></script>
    <![endif]-->
    <!-- js placed at the end of the document so the pages load faster -->
    <script src="{{ static_url('js/jquery.js')}}"></script>
    <script src="{{ static_url('js/jquery-1.8.3.min.js')}}"></script>
    <script src="{{ static_url('js/bootstrap.min.js')}}"></script>
    <script class="include" type="text/javascript" src="{{ static_url('js/jquery.dcjqaccordion.2.7.js')}}"></script>
    <script src="{{ static_url('js/jquery.scrollTo.min.js')}}"></script>
    <script src="{{ static_url('js/jquery.nicescroll.js')}}" type="text/javascript"></script>
    <script src="{{ static_url('js/jquery.sparkline.js')}}" type="text/javascript"></script>
    <script src="{{ static_url('assets/jquery-easy-pie-chart/jquery.easy-pie-chart.js')}}"></script>
    <script src="{{ static_url('js/owl.carousel.js')}}" ></script>
    <script src="{{ static_url('js/jquery.customSelect.min.js')}}" ></script>
    <script src="{{ static_url('js/respond.min.js')}}" ></script>
    <script class="include" type="text/javascript" src="{{ static_url('js/jquery.dcjqaccordion.2.7.js')}}"></script>
    <!--common script for all pages-->
    <script src="{{ static_url('js/common-scripts.js')}}"></script>
    <!--script for this page-->
    <script src="{{ static_url('js/sparkline-chart.js')}}"></script>
    <script src="{{ static_url('js/easy-pie-chart.js')}}"></script>
    <script src="{{ static_url('js/count.js')}}"></script>
    <script src="{{ static_url('js/template.js')}}"></script>
    <script>
        var ajax = function (url,type,data) {
            var res = '';
            $.ajax({
                url:url,
                type:type,
                data:data,
                dataType:'json',
                async:false,
                success:function(result){
                    if(result.code != 0){
                        console.log('result.code 不等于0');
                    }
                    res =result;
                },
                error:function (err) {
                    console.log('ajax出错了');
                    console.log(err);
                }
            });
            return res;
        };
        var init_select = function (name,data) {
            var str='';
            for (var i = 0; i < data.length; i++) {
                str += '<option value="'+data[i].type+'">'+data[i].name+'</option>'
            }
            $('select[name='+name+']').html(str);
        };
        var tpl = function (id, html, list) {
            document.getElementById(html).innerHTML = template(id, {list: list});
        };
        var host = "http://193.112.8.195/admin/";
    </script>
</head>